services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallets
    ports:
      - "5432:5432"
    networks:
      - dope-net
  meta-server:
    build: ./dope-meta-server
    restart: always
    environment:
      PORT: 80
    ports:
      - "8081:80"
    networks:
      - dope-net


networks:
  dope-net:
